### Multi Dimensional Array

In [58]:
import numpy as np

In [59]:
a_2d=np.array([[10,20,30],[23,55,30]])


In [60]:
a_2d

array([[10, 20, 30],
       [23, 55, 30]])

In [61]:
a_2d.dtype

dtype('int64')

In [62]:
a_2d.shape

(2, 3)

In [63]:
a_2d.ndim

2

In [64]:
a_2d.size

6

In [65]:
a_2d[0]

array([10, 20, 30])

### Another Type Of Multi Dimensional Arrays

In [66]:
another_type_array=np.array([[[1,2,3,4]]])


In [67]:
another_type_array

array([[[1, 2, 3, 4]]])

In [68]:
another_type_array.shape

(1, 1, 4)

In [69]:
another_type_array.ndim

3

In [70]:
another_type_array.size

4

In [71]:
another_type_array[0]

array([[1, 2, 3, 4]])

### Access Elements in Multi Diamensional Array

In [72]:
#First Element in First Array
a_2d=np.array([[10,20,30],[23,55,30]])


In [73]:
a_2d[0][0]

np.int64(10)

In [74]:
#Second Element in Second Array
a_2d[1][1]

np.int64(55)

In [75]:
#Third Element in First Array
a_2d[0][2]

np.int64(30)

In [76]:
#First Element in Second Array
a_2d[1][0]

np.int64(23)

In [77]:
#Second Element in First Array
a_2d[0][1]

np.int64(20)

### Changing Datatype

In [78]:
a_2d

array([[10, 20, 30],
       [23, 55, 30]])

In [79]:
a_2d.astype(float)

array([[10., 20., 30.],
       [23., 55., 30.]])

In [80]:
# Changing Datatype at the time of creation
a_2d=np.array([[10,20,30],[23,55,30]],dtype=float)
a_2d

array([[10., 20., 30.],
       [23., 55., 30.]])

### Lets Create a Bigger Array

In [81]:
a_bigger=np.array([
[
[10,20,30,40],[8,7,5,4],[2,4,6,8]
],
[
[22,42,32,52],[12,22,43,67],[11,45,35,66]
],
[
[70,80,90,95],[70,72,82,62],[10,20,25,15]
]
],dtype=float)

In [82]:
a_bigger

array([[[10., 20., 30., 40.],
        [ 8.,  7.,  5.,  4.],
        [ 2.,  4.,  6.,  8.]],

       [[22., 42., 32., 52.],
        [12., 22., 43., 67.],
        [11., 45., 35., 66.]],

       [[70., 80., 90., 95.],
        [70., 72., 82., 62.],
        [10., 20., 25., 15.]]])

In [83]:
a_bigger.shape

(3, 3, 4)

In [84]:
a_bigger.ndim

3

In [85]:
a_bigger.size

36

In [86]:
#
a_bigger[0][0][1]

np.float64(20.0)

In [87]:
a_bigger[1][0][2]

np.float64(32.0)

In [88]:
a_bigger[2][1][0]

np.float64(70.0)

In [89]:
a_bigger[2][0]

array([70., 80., 90., 95.])

In [90]:
a_bigger[0][2]

array([2., 4., 6., 8.])

### Filling Arrays

In [91]:
af=np.full((2,3,3),4)
af

array([[[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]],

       [[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]]])

In [92]:
af.ndim

3

In [93]:
af.size

18

In [94]:
af.shape

(2, 3, 3)

In [117]:
af1=np.full((3,5,4),15)
af1

array([[[15, 15, 15, 15],
        [15, 15, 15, 15],
        [15, 15, 15, 15],
        [15, 15, 15, 15],
        [15, 15, 15, 15]],

       [[15, 15, 15, 15],
        [15, 15, 15, 15],
        [15, 15, 15, 15],
        [15, 15, 15, 15],
        [15, 15, 15, 15]],

       [[15, 15, 15, 15],
        [15, 15, 15, 15],
        [15, 15, 15, 15],
        [15, 15, 15, 15],
        [15, 15, 15, 15]]])

### Zeros And Ones

In [95]:
az=np.zeros((2,3))
az

array([[0., 0., 0.],
       [0., 0., 0.]])

In [96]:
az.ndim

2

In [97]:
az.size

6

In [98]:
a1=np.ones((3,4))
a1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [99]:
a1.ndim

2

In [100]:
a1.size

12

In [120]:
a_one=np.ones((3,5,4))
a_one

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [118]:
az1=np.zeros((4,3))
az1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Empty And Random

In [116]:
ae=np.empty((2,2))
ae

array([[1., 1.],
       [1., 1.]])

In [102]:
ar=np.random.random((2,2))
ar

array([[0.41784353, 0.70737758],
       [0.96774119, 0.1126342 ]])

In [103]:
ar.ndim

2

In [104]:
ar.size

4

## RANGES

### Arange

In [105]:
a_arange=np.arange(2,21,2)
a_arange

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [122]:
# print all odd numbers 1 to 20
a_arange2=np.arange(1,21,2)
a_arange2

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [123]:
# print all even numbers 1 to 30
a_arange3=np.arange(2,31,2)
a_arange3

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

### Linspace

In [106]:
a_linspace=np.linspace(0,20,10,dtype=int)
a_linspace

array([ 0,  2,  4,  6,  8, 11, 13, 15, 17, 20])

In [107]:
a_linspace.ndim

1

In [108]:
a_linspace.shape

(10,)

In [109]:
a_linspace.size

10

In [110]:
a_linspace2=np.linspace(0,10,2)
a_linspace2

array([ 0., 10.])

In [125]:
a_linspace1=np.linspace(1,10,5,dtype=int)
a_linspace1

array([ 1,  3,  5,  7, 10])

### Identity Matrix

In [111]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [112]:
# anothr method
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])