### MATH FUNCTIONS

In [2]:
import numpy as np

In [3]:
a=np.array([10,20,30,40,50])
a

array([10, 20, 30, 40, 50])

In [4]:
np.exp(a)

array([2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 2.35385267e+17,
       5.18470553e+21])

In [5]:
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485])

In [6]:
np.cos(a)

array([-0.83907153,  0.40808206,  0.15425145, -0.66693806,  0.96496603])

In [7]:
np.tan(a)

array([ 0.64836083,  2.23716094, -6.4053312 , -1.11721493, -0.27190061])

In [8]:
np.log(a)

array([2.30258509, 2.99573227, 3.40119738, 3.68887945, 3.91202301])

In [9]:
np.sqrt(a)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

### AGGREGATE FUNCTIONS

In [10]:
a

array([10, 20, 30, 40, 50])

In [11]:
a.sum()

np.int64(150)

In [12]:
a.min()

np.int64(10)

In [13]:
a.max()

np.int64(50)

In [14]:
a.mean()

np.float64(30.0)

In [15]:
np.median(a)

np.float64(30.0)

In [16]:
np.std(a)

np.float64(14.142135623730951)