### Import Numpy

In [1]:
import numpy as np

In [2]:
a=np.array([10,20,30])
a

array([10, 20, 30])

In [4]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [5]:
# find version of numpy
print(np.__version__)

2.3.5


### Array Slicing

In [7]:
a=np.array([10,20,30,40,50])
print(a[1:4])

[20 30 40]


In [8]:
a=np.array([[10,20,30],
            [40,50,60]])
print(a[:,1:])


[[20 30]
 [50 60]]


### Data Types

In [12]:
a=np.array([10,20,30],dtype=float)
print(a)
print(a.dtype)

[10. 20. 30.]
float64


### Array Reshaping

In [13]:
a=np.array([10,20,30,40,50,60])
print(a.reshape(2,3))

      

[[10 20 30]
 [40 50 60]]


In [17]:
a=np.array([[1,2],
            [4,5]])
print(a.reshape(4))
           

[1 2 4 5]


### Random Module

In [ ]:
# .random.seed(0) is used to dont change random values
np.random.seed(0)


In [18]:
print(np.random.rand(5))

[0.3179725  0.0927122  0.47196079 0.71736555 0.47310707]


In [19]:
print(np.random.randint(1,10,5))

[5 3 3 5 1]


In [20]:
print(np.random.randn(5))

[-0.01621488 -0.14331297 -1.40528854  0.73791128 -1.93114357]


In [23]:
print(np.random.choice([10,20,30],5))

[30 10 10 10 20]


### Array Iterating


In [24]:
a=np.array([10,20,30])
for i in a:
    print(i)

10
20
30


In [26]:
# Array iterating in multidiamensional array
a=np.array([[10,20],
           [30,40]])
for i in np.nditer(a):
    print(i)


10
20
30
40


### Joining Arrays

In [27]:
a=np.array([1,2])
b=np.array([3,4])
print(np.concatenate((a,b)))

[1 2 3 4]


In [28]:
# array joining with stack()
a=np.array([1,2])
b=np.array([3,4])
print(np.stack((a,b)))

[[1 2]
 [3 4]]


In [29]:
# array joining with vstack()
a=np.array([1,2])
b=np.array([3,4])
print(np.vstack((a,b)))

[[1 2]
 [3 4]]


In [30]:
# array joining with hstack()
a=np.array([1,2])
b=np.array([3,4])
print(np.hstack((a,b)))

[1 2 3 4]


### Spliting Arrays

In [32]:
a=np.array([1,2,3,4])
print(np.array_split(a,2))

[array([1, 2]), array([3, 4])]


### Searching Arrays

In [33]:
a=np.array([10,20,30,20,10])
print(np.where(a==20))

(array([1, 3]),)


In [34]:
a=np.array([5,8,10,15])
print(np.where(a>8))

(array([2, 3]),)


### Sorting Arrays

In [35]:
a=np.array([20,10,40,30,50])
print(np.sort(a))

[10 20 30 40 50]


In [36]:
a=np.array(["Banana","Apple","cherry"])
print(np.sort(a))

['Apple' 'Banana' 'cherry']


### Filter Arrays

In [38]:
a=np.array([10,20,25,30,35,40])
print(a[a>25])

[30 35 40]


In [41]:
a=np.array([1,2,3,4,5,6])
print(a[a % 2==0])

[2 4 6]


### Array Mathematics

In [42]:
a=np.array([10,20,30])
b=np.array([1,2,3,])
print(a+b)
print(a-b)
print(a*2)
print(a**2)
print(a//2)

[11 22 33]
[ 9 18 27]
[20 40 60]
[100 400 900]
[ 5 10 15]


### Axis Concept

In [45]:
a=np.array([[1,2,3],
            [4,5,6]])
print(np.sum(a,axis=0))#column wise
print(np.sum(a,axis=1))#row wise

[5 7 9]
[ 6 15]
