### NUMPY ADVANCED TASK

In [10]:
import numpy as np

In [4]:
# 1. Create a NumPy array containing 10, 20, 30, 40, 50 . Display the array, its shape, data type, size of each element, and total memory used.
a=np.array([10,20,30,40,50])
print(a)
print("Shape :",a.shape)
print("Data Type: ",a.dtype)
print("Size of each Elements :",a.itemsize)
print("Total Memory Used: ",a.nbytes)

[10 20 30 40 50]
Shape : (5,)
Data Type:  int64
Size of each Elements : 8
Total Memory Used:  40


In [5]:
# 2. Create a 3 × 4 array containing the numbers from 1 to 12 . Display the second and third rows.
a=np.arange(1,13)
a=a.reshape(3,4)
print(a)
print(a[1:3,:])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
# 3. Create an array containing the numbers from 1 to 12 and convert it into a 3 × 4 array.
a=np.arange(1,13)
a=a.reshape(3,4)
print(a)



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
# 4. Create two arrays containing [10, 20, 30] and [40, 50, 60] . Combine them so that the result contains two rows.
a=np.array([10,20,30])
b=np.array([40,50,60])
print(np.vstack((a,b)))


[[10 20 30]
 [40 50 60]]


In [8]:
# 5. Divide the array [10, 20, 30, 40, 50] into three smaller arrays.
a=np.array([10,20,30,40,50])
print(np.array_split(a,3))

[array([10, 20]), array([30, 40]), array([50])]


In [11]:
# 6. Given the array [5, 10, 15, 20, 25, 30] , display the positions of all elements greater than 15 .
a=np.array([5,10,15,20,25,30])
print(np.where(a>15))


(array([3, 4, 5]),)


In [14]:
# 7. Given the array [12, 5, 20, 8, 30, 15] , display only the values between 10 and 25 .
a=np.array([12,5,20,8,30,15])
print(a[(a>10) & (a<25)])


[12 20 15]


In [15]:
# 8. Given the array [4, 9, 16, 25] , calculate the square root of every element.
a=np.array([4,9,16,25])
print(np.sqrt(a))

[2. 3. 4. 5.]


In [18]:
# 9. Given the array [1, 2, 3, 4] , calculate the exponential value and natural logarithm of every element.
a=np.array([1,2,3,4])
print(np.exp(a))
print(np.log(a))


[ 2.71828183  7.3890561  20.08553692 54.59815003]
[0.         0.69314718 1.09861229 1.38629436]


In [26]:
# 10. Given the array [10, 20, 30, 40, 50] , find the total, average, median,standard deviation, variance, smallest value, and largest value.
a=np.array([10,20,30,40,50])
print("Total: ",np.sum(a))
print("Average : ",np.mean(a))
print("Median : ",np.median(a))
print("Standard Deviation : ",np.std(a))
print("Variance : ",np.var(a))
print("Smallest Value: ",np.min(a))
print("Largest Value: ",np.max(a))

Total:  150
Average :  30.0
Median :  30.0
Standard Deviation :  14.142135623730951
Variance :  200.0
Smallest Value:  10
Largest Value:  50


In [28]:
# 11. Given the array [10, 20, 5, 40, 15] , find the positions of the smallest and largest elements.
a=np.array([10, 20, 5, 40, 15])
print("Position of Smallest Element: ",np.argmin(a))
print("Position of Largest Element: ",np.argmax(a))


Position of Smallest Element:  2
Position of Largest Element:  3


In [58]:
# 12 Find the sum of the values in each row and the sum of the values in each column.
a=np.array([[2, 4, 6],
            [8, 10, 12]])
print("Sum Of First Row :",np.sum(a[0,:]))
print("Sum Of Second Row :",np.sum(a[1,:]))
print("Sum Of First Column :",np.sum(a[:,0]))
print("Sum Of Second Column :",np.sum(a[:,1]))
print("Sum Of Third Column :",np.sum(a[:,2]))



Sum Of First Row : 12
Sum Of Second Row : 30
Sum Of First Column : 10
Sum Of Second Column : 14
Sum Of Third Column : 18


In [71]:
# 13. Create an array containing [10, 20, 30, 40] . Create a separate copy and a view of the array. Modify the arrays and observe the effect on the original array
a=np.array([10,20,30,40])
b=a.copy()
c=a.view()
b[0]=5
c[2]=25
print(a)
print(b)
print(c)

[10 20 25 40]
[ 5 20 30 40]
[10 20 25 40]


In [74]:
# 14. Generate five random decimal numbers, five random integers between 1 and 20 , and five values from the list [10, 20, 30, 40] .
a=np.random.rand(5)
b=np.random.randint(1,20,5)
c=np.random.choice([10,20,30,40],5)
print(a)
print(b)
print(c)

[0.44501433 0.58452168 0.04912147 0.49139149 0.57926518]
[12  3  8  7 10]
[10 40 20 30 20]


In [83]:
# 15 Print every element one by one, then convert the array into a one-dimensional array
a=np.array([[1,2,3],
            [4,5,6]])
for i in np.nditer(a):
    print(i)
print(a.flatten())
           


1
2
3
4
5
6
[1 2 3 4 5 6]


In [79]:
# 16. Given the array [35, 10, 60, 25, 5, 45] , arrange the elements in ascending order
a=np.array([35, 10, 60, 25, 5, 45])
print("Ascending Order :",np.sort(a))


Ascending Order : [ 5 10 25 35 45 60]


In [80]:
# 17. Given the array ["Mango", "Apple", "Grapes", "Banana", "Orange"] , arrange the elements in alphabetical order.
a=np.array(["Mango", "Apple", "Grapes", "Banana", "Orange"])
print("Alphabetical Order :",np.sort(a))


Alphabetical Order : ['Apple' 'Banana' 'Grapes' 'Mango' 'Orange']


In [82]:
# 18. Create a NumPy array containing [10, 20, 30, 40, 50, 60] . Divide the array into four smaller arrays.
a=np.array([10, 20, 30, 40, 50, 60])
print(np.array_split(a,4))

[array([10, 20]), array([30, 40]), array([50]), array([60])]


In [85]:
# 19. Create two arrays containing [1, 2, 3] and [4, 5, 6] . Combine them horizontally so that the result is a single row containing all six elements.
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.hstack((a,b)))


[1 2 3 4 5 6]


In [90]:
# 20. Create a NumPy array containing [10, 20, 30, 40, 50] . Perform addition,subtraction, multiplication, division, and squaring operations on the array.
a=np.array( [10, 20, 30, 40, 50])
print("Addition :",a+5)
print("Substraction :",a-5)
print("Multiplication :",a*5)
print("Division :",a/5)
print("Square :",a**2)


Addition : [15 25 35 45 55]
Substraction : [ 5 15 25 35 45]
Multiplication : [ 50 100 150 200 250]
Division : [ 2.  4.  6.  8. 10.]
Square : [ 100  400  900 1600 2500]
